title: Arduino PS
description: Arduino Power Supply
baseurl: "/arduino_adjustable_power_supply" # the subpath of your site, e.g. /blog
url: "https://edmugu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: pmarsceill/just-the-docs



# Aux links for the upper right navigation
aux_links:
  "Link to GitHub":
    - "//github.com/edmugu/arduino_adjustable_power_supply"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false


# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    docs:
      # Give the collection a name
      name: Documentation
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
