remote_theme: pmarsceill/just-the-docs


# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/jekyll_docs"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    docs:
      # Give the collection a name
      name: Documentation
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false

# Aux links for the upper right navigation
aux_links:
  "Link to GitHub":
    - "//github.com/edmugu/arduino_adjustable_power_supply"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
